export const 
api = {
    am: [
      { url: "http://cdn.instream.audio:9288/stream", 
        nombre: "Radio Madre", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/m6rhm9jvctg5.jpg",
        frecuencia: 530 },
      { url: "https://streaming1.hostingmontevideo.com:7019/", 
        nombre: "Radio Colonia", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/86e8ctdpza.jpg",
        frecuencia: 550 },
      { url: "http://server.laradio.online:25224/live.mp3", 
        nombre: "Radio Argentina", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/Y7F2cu34He.png",
        frecuencia: 570 },
      { url: "http://playerservices.streamtheworld.com/api/livestream-redirect/CONTINENTAL_SC", 
        nombre: "Continental", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/43xHVSbHNX.png",
        frecuencia: 590 },
      { url: "https://streammax.alsolnet.com/radiorivadavia", 
        nombre: "Rivadavia", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/dezhxnb3mzrf.png",
        frecuencia: 630 },
      { url: "http://server.laradio.online:25223/live.mp3", 
        nombre: "Belgrano-650", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/b942cecxy6wn.png",
        frecuencia: 650 },
      { url: "http://s6.stweb.tv/radio10/live/playlist.m3u8", 
        nombre: "Radio 10", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/H5DXfLuQV2.jpg",
        frecuencia: 710 },
      { url: "http://servidor.01argentina.com.ar:6358", 
        nombre: "Radio Rebelde", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/jahvvj2kgwb9.png",
        frecuencia: 740 },
      { url: "http://192.99.38.174:9342/stream", 
        nombre: "AM 750", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/Pg5tZKG6WX.jpg",
        frecuencia: 750 },
      { url: "http://rcoop.cnwks.ws:8358", 
        nombre: "Cooperativa", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/YEQ7Rf2TJG.png",
        frecuencia: 770 },
      { url: "https://buecrplb01.cienradios.com.ar/Mitre790.aac", 
        nombre: "Radio Mitre", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/nunnxe6yudtc.jpg",
        frecuencia: 790 },
      { url: "http://streaming.radiolinksmedia.com:7830/;", 
        nombre: "Del Pueblo", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/HwyPdaJKpc.jpeg",
        frecuencia: 830 },
      { url: "http://sa.mp3.icecast.magma.edge-access.net:7200/sc_rad1", 
        nombre: "Radio Nacional", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/6hnHR4JXtH.jpg",
        frecuencia: 870 },
      { url: "https://streamten.alsolnet.com/la990", 
        nombre: "la990", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/mb7F4ZGPXX.jpg",
        frecuencia: 990 },
      { url: "http://181.119.157.98:8000/amdelplata.mp3", 
        nombre: "Del Plata", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/DmkFm3kbdq.png",
        frecuencia: 1030 },
      { url: "http://nnvserver.com:8032/stream", 
        nombre: "Güemes", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/qqynsttgaz6n.png",
        frecuencia: 1050 },
      { url: "http://radios.argentina.fm:1110/stream", 
        nombre: "De la ciudad", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/GfDX9MHAVg.png",
        frecuencia: 1110 },
      { url: "http://ample-zeno-09.radiojar.com/uv3vkhw2qvduv", 
        nombre: "Eco medios", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/TUVTYXhvqt.png",
        frecuencia: 1220 },
    ],
    fm: [
      { url: "http://vivo.fmlatribu.com:8000/latribu.mp3", 
        nombre: "La Tribu", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/erpW87DyX5.jpeg",
        frecuencia: 88.7 },
      { url: "http://vivo.radioam750.com.ar/vivofm.mp3", 
        nombre: "Malena", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/NccVZhZk8B.png",
        frecuencia: 89.1 },
      { url: "http://14073.live.streamtheworld.com/ARPEGGIOAAC", 
        nombre: "Arpeggio", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/gw4s8rgtey7b.jpg",
        frecuencia: 89.5 },
      { url: "http://server6.stweb.tv:1935/rcvos/live/playlist.m3u8", 
        nombre: "Radio con vos", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/aV5EbVu2dM.jpg",
        frecuencia: 89.9 },
      { url: "http://208.98.41.72:9304", 
        nombre: "La Boca", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/AVz87KL7sX.png",
        frecuencia: 90.1 },
      { url: "https://cdn.instream.audio/:9069/stream", 
        nombre: "Delta", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/8scHa5pfGj.jpg",
        frecuencia: 90.3 },
      { url: "http://147.135.11.82:9904/;", 
        nombre: "Vorterix", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/ymjzgkacrsty.jpg",
        frecuencia: 92.1 },
      { url: "http://radios.argentina.fm:9270/stream", 
        nombre: "La 2x4", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/pg3xzk6yjmjr.jpg",
        frecuencia: 92.7 },
      { url: "http://streaming.radiolinksmedia.com:8252/;stream", 
        nombre: "Late", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/drgtypfqh49q.jpg",
        frecuencia: 93.1 },
      { url: "http://sa.mp3.icecast.magma.edge-access.net:7200/sc_rad39", 
        nombre: "Nacional Rock", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/GrZV3kE9rP.jpg",
        frecuencia: 93.7 },
      { url: "https://edge-np.cdn.mdstrm.com/5a9ee26311c043ae48e40bcd.mp3", 
        nombre: "RadioDisney", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/7kh84bfketx3.jpg",
        frecuencia: 94.3 },
      { url: "http://24363.live.streamtheworld.com:80/METRO_SC", 
        nombre: "Metro", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/ajPmNWn4WN.jpg",
        frecuencia: 95.1 },
      { url: "http://servidor.ilive.com.ar:9330/;", 
        nombre: "Concepto", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/dt9djnnwzx5z.jpg",
        frecuencia: 95.5 },
      { url: "https://playerservices.streamtheworld.com/api/livestream-redirect/ROCKANDPOP.mp3", 
        nombre: "Rock & Pop", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/zdW6jjDrDq.jpg",
        frecuencia: 95.9 },
      { url: "http://sa.mp3.icecast.magma.edge-access.net:7200/sc_rad37", 
        nombre: "Nacional Clásica", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/t9ef5y8r8mtq.png",
        frecuencia: 96.7 },
      { url: "http://18543.live.streamtheworld.com/MUCHARADIO_SC", 
        nombre: "Mucha radio", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/xjnztg4mj7yt.png",
        frecuencia: 97.1 },
      { url: "http://vale.stweb.tv:1935/vale/live/playlist.m3u8", 
        nombre: "Vale", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/vgfSxMP2xK.png",
        frecuencia: 97.5 },
      { url: "https://usa5.fastcast4u.com/proxy/radiocultura", 
        nombre: "Cultura", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/uaTRZKBJF8.jpg",
        frecuencia: 97.9 },
      { url: "https://mega.stweb.tv/mega983/live/playlist.m3u8", 
        nombre: "Mega", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/T6DPeFDmYv.jpg",
        frecuencia: 98.3 },
      { url: "http://sa.mp3.icecast.magma.edge-access.net:7200/sc_rad38", 
        nombre: "Nacional Folklorica", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/GTYTv4CKk3.png",
        frecuencia: 98.7 },
      { url: "https://playerservices.streamtheworld.com/api/livestream-redirect/FM999_56.mp3", 
        nombre: "La 100", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/DWgcTuX4BP.jpg",
        frecuencia: 99.9 },
      { url: "http://streaming.latina101.com.ar:8080/RadioLatina", 
        nombre: "Latina", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/JuGenenpuW.png",
        frecuencia: 101.1 },
      { url: "https://www.radios-argentinas.org/radio-pop-1015", 
        nombre: "Pop", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/WmnW6kEgFQ.png",
        frecuencia: 101.5 },
      { url: "http://server4.stweb.tv:1935/lapatriada/live/playlist.m3u8", 
        nombre: "La patriada", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/jnumxvk2x9yu.png",
        frecuencia: 102.1 },
      { url: "https://mdstrm.com/audio/60a2745ff943100826374a70/icecast.audio", 
        nombre: "Aspen", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/nmUy6cegN2.png",
        frecuencia: 102.3 },
      { url: "http://209.95.35.49:7013/live", 
        nombre: "Radio Uno", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/dYBEPUwPvK.png",
        frecuencia: 103.1 },
      { url: "http://streamall.alsolnet.com:443/klimaxok", 
        nombre: "Klimax", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/eeqyzhbhzzbh.jpg",
        frecuencia: 103.5 },
      { url: "https://s8.stweb.tv/one/live/playlist.m3u8", 
        nombre: "One", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/AKeckFhWLs.jpg",
        frecuencia: 103.7 },
      { url: "http://14933.live.streamtheworld.com/RQPAAC ", 
        nombre: "RQP", 
        imagen:"https://static.mytuner.mobi/media/tvos_radios/m558hst42z5m.jpg",
        frecuencia: 104.3 },
      { url: "https://26643.live.streamtheworld.com:443/LOS40_ARGENTINAAAC_SC", 
        nombre: "Los 40", 
        imagen:"https://static.mytuner.mobi/media/radios-150px/wnQePCrWJ2.png",
        frecuencia: 105.5 },
    ],
  };
  
  