export const 
api = {
    am: [
      { url: "http://cdn.instream.audio:9288/stream", 
        nombre: "Radio Madre", 
        frecuencia: 530 },
      { url: "https://streaming1.hostingmontevideo.com:7019/", 
        nombre: "Radio Colonia", 
        frecuencia: 550 },
      { url: "http://server.laradio.online:25224/live.mp3", 
        nombre: "Radio Argentina", 
        frecuencia: 570 },
      { url: "http://playerservices.streamtheworld.com/api/livestream-redirect/CONTINENTAL_SC", 
        nombre: "Continental", 
        frecuencia: 590 },
      { url: "https://streammax.alsolnet.com/radiorivadavia", 
        nombre: "Rivadavia", 
        frecuencia: 630 },
      { url: "http://server.laradio.online:25223/live.mp3", 
        nombre: "Belgrano-650", 
        frecuencia: 650 },
      { url: "http://s6.stweb.tv/radio10/live/playlist.m3u8", 
        nombre: "Radio 10", 
        frecuencia: 710 },
      { url: "http://servidor.01argentina.com.ar:6358", 
        nombre: "Radio Rebelde", 
        frecuencia: 740 },
      { url: "http://192.99.38.174:9342/stream", 
        nombre: "AM 750", 
        frecuencia: 750 },
      { url: "http://rcoop.cnwks.ws:8358", 
        nombre: "Cooperativa", 
        frecuencia: 770 },
      { url: "https://buecrplb01.cienradios.com.ar/Mitre790.aac", 
        nombre: "Radio Mitre", 
        frecuencia: 790 },
      { url: "http://streaming.radiolinksmedia.com:7830/;", 
        nombre: "Del Pueblo", 
        frecuencia: 830 },
      { url: "http://sa.mp3.icecast.magma.edge-access.net:7200/sc_rad1", 
        nombre: "Radio Nacional", 
        frecuencia: 870 },
      { url: "https://streamten.alsolnet.com/la990", 
        nombre: "la990", 
        frecuencia: 990 },
      { url: "http://181.119.157.98:8000/amdelplata.mp3", 
        nombre: "Del Plata", 
        frecuencia: 1030 },
      { url: "http://nnvserver.com:8032/stream", 
        nombre: "Güemes", 
        frecuencia: 1050 },
      { url: "http://radios.argentina.fm:1110/stream", 
        nombre: "De la ciudad", 
        frecuencia: 1110 },
      { url: "http://server.ohradio.com.ar:9344/;", 
        nombre: "Radio La Luna", 
        frecuencia: 1140 },
      { url: "http://ample-zeno-09.radiojar.com/uv3vkhw2qvduv", 
        nombre: "Eco medios", 
        frecuencia: 1220 },
    ],
    fm: [
      { url: "http://vivo.fmlatribu.com:8000/latribu.mp3", 
        nombre: "La Tribu", 
        frecuencia: 88.7 },
      { url: "http://vivo.radioam750.com.ar/vivofm.mp3", 
        nombre: "Malena", 
        frecuencia: 89.1 },
      { url: "http://14073.live.streamtheworld.com/ARPEGGIOAAC", 
        nombre: "Arpeggio", 
        frecuencia: 89.5 },
      { url: "http://server6.stweb.tv:1935/rcvos/live/playlist.m3u8", 
        nombre: "Radio con vos", 
        frecuencia: 89.9 },
      { url: "http://208.98.41.72:9304", 
        nombre: "La Boca", 
        frecuencia: 90.1 },
      { url: "https://cdn.instream.audio/:9069/stream", 
        nombre: "Delta", 
        frecuencia: 90.3 },
      { url: "http://147.135.11.82:9904/;", 
        nombre: "Vorterix", 
        frecuencia: 92.1 },
      { url: "http://209.95.35.49:7240/Stream", 
        nombre: "Zero", 
        frecuencia: 92.5 },
      { url: "http://radios.argentina.fm:9270/stream", 
        nombre: "La 2x4", 
        frecuencia: 92.7 },
      { url: "http://streaming.radiolinksmedia.com:8252/;stream", 
        nombre: "Late", 
        frecuencia: 93.1 },
      { url: "http://sa.mp3.icecast.magma.edge-access.net:7200/sc_rad39", 
        nombre: "Nacional Rock", 
        frecuencia: 93.7 },
      { url: "https://edge-np.cdn.mdstrm.com/5a9ee26311c043ae48e40bcd.mp3", 
        nombre: "RadioDisney", 
        frecuencia: 94.3 },
      { url: "http://mp3.metroaudio1.stream.avstreaming.net:7200/metro", 
        nombre: "Metro", 
        frecuencia: 95.1 },
      { url: "http://servidor.ilive.com.ar:9330/;", 
        nombre: "Concepto", 
        frecuencia: 95.5 },
      { url: "http://play-rockandpop.cdn.sion.com:1935/rockandpop/audioweb/playlist.m3u8", 
        nombre: "Rock & Pop", 
        frecuencia: 95.9 },
      { url: "http://sa.mp3.icecast.magma.edge-access.net:7200/sc_rad37", 
        nombre: "Nacional Clásica", 
        frecuencia: 96.7 },
      { url: "http://18543.live.streamtheworld.com/MUCHARADIO_SC", 
        nombre: "Mucha radio", 
        frecuencia: 97.1 },
      { url: "http://vale.stweb.tv:1935/vale/live/playlist.m3u8", 
        nombre: "Vale", 
        frecuencia: 97.5 },
      { url: "https://usa5.fastcast4u.com/proxy/radiocultura", 
        nombre: "Cultura", 
        frecuencia: 97.9 },
      { url: "https://server1.stweb.tv/mega983/live/chunks.m3u8", 
        nombre: "Mega", 
        frecuencia: 98.3 },
      { url: "http://sa.mp3.icecast.magma.edge-access.net:7200/sc_rad38", 
        nombre: "Nacional Folklorica", 
        frecuencia: 98.7 },
      { url: "http://retransmisorasenelpais.cienradios.com.ar:8000/la100.aac", 
        nombre: "La 100", 
        frecuencia: 99.9 },
      { url: "https://blue.secure2.footprint.net/egress/bhandler/streamroot_lsd2latam/blue/chunklist_b98304.m3u8", 
        nombre: "Blue", 
        frecuencia: 100.7 },
      { url: "http://streaming.latina101.com.ar:8080/RadioLatina", 
        nombre: "Latina", 
        frecuencia: 101.1 },
      { url: "https://s8.stweb.tv/popradio/live/playlist.m3u8", 
        nombre: "Pop", 
        frecuencia: 101.5 },
      { url: "http://server4.stweb.tv:1935/lapatriada/live/playlist.m3u8", 
        nombre: "La patriada", 
        frecuencia: 102.1 },
      { url: "http://playerservices.streamtheworld.com/api/livestream-redirect/ASPENAAC", 
        nombre: "Aspen", 
        frecuencia: 102.3 },
      { url: "http://209.95.35.49:7013/live", 
        nombre: "Radio Uno", 
        frecuencia: 103.1 },
      { url: "http://streamall.alsolnet.com:443/klimaxok", 
        nombre: "Klimax", 
        frecuencia: 103.5 },
      { url: "http://streamall.alsolnet.com:443/fmsonidohd?type=.flv", 
        nombre: "Sonido", 
        frecuencia: 103.5 },
      { url: "http://s11.stweb.tv/one/live/playlist.m3u8", 
        nombre: "One", 
        frecuencia: 103.7 },
      { url: "http://14933.live.streamtheworld.com/RQPAAC", 
        nombre: "RQP", 
        frecuencia: 104.3 },
      { url: "http://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_ARGENTINAAAC", 
        nombre: "Los 40", 
        frecuencia: 105.5 },
      { url: "http://108.59.9.147/proxy/arvlyxui", 
        nombre: "Milenium", 
        frecuencia: 106.7 },
      { url: "http://edge.espn.cdn.abacast.net/espn-deportesmp3-48", 
        nombre: "ESPN", 
        frecuencia: 107.9 },
    ],
  };
  
  